name: Commnader_Wars
on: [push]
env:
  BUILD_TYPE: Release
  QT_Version: '6.8.1'
  workspace: 'D:/a/Commander_Wars/Commander_Wars'
  JAVA_PATH: 'C:/hostedtoolcache/windows/Java_Temurin-Hotspot_jdk/17.0.14-7/x64/'
  ANDROID_OPEN_SSL_TAG: '57056d6dd94c235a67b1bc0e4befdba8f9e11c8d'
  
jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{steps.create_release.outputs.upload_url}}
    steps:
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/Beta')
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        with:
          tag_name: ${{github.ref}}
          release_name: Release ${{github.ref}}  
          draft: false
          prerelease: true        
          body: | 
            Latest Commander Wars Release 
            See the github wiki for the related change log:
            https://github.com/Robosturm/Commander_Wars/wiki
            
  install:
    name: All
    strategy:
      fail-fast: false
      matrix:
        buildTarget: [macos-desktop]
        include:
          - buildTarget: macos-desktop
            os: macos-latest
            COMPILER_VERSION: 'clang_64'
            qtPath: 'clang_64'
            qtTools: ''
            target: 'desktop'
            installerCommands1: ''
            installerCommands2: ''
            source_asset: 'Commander_Wars.zip'
            asset_file: 'Commander_Wars-macOS'
            asset_name: 'Commander_Wars-macOS-${{github.ref_name}}.zip'
            cmakeOptions: '-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64"'

    needs: create_release
    
    runs-on: ${{matrix.os}}
    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout source code
      uses: actions/checkout@v4
      with:
          path: 'source'
          submodules: 'true'

    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:     
          aqtversion: '==3.1.*'
          target: ${{matrix.target}}
          version: ${{env.QT_Version}}
          arch: ${{matrix.COMPILER_VERSION}}
          modules: 'qtmultimedia'
          dir: '${{github.workspace}}/qt/'
          install-deps: "true"
          tools: '${{matrix.qtTools}}'
          set-env: 'true'
                
    - name: Install OS Dependencies 1
      run: ${{matrix.installerCommands1}}
    
    - name: Install OS Dependencies 2
      run: ${{matrix.installerCommands2}}

#----------------------------------------------------------------------------------------------------------------------------------------------
# release creation and upload part
#----------------------------------------------------------------------------------------------------------------------------------------------
        
    - name: upload other artifacts
      if: matrix.target != 'android' && matrix.linuxFlag != 'linux' && startsWith(github.ref, 'refs/tags/Beta')
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{github.token}}
      with:
        upload_url: '${{needs.create_release.outputs.upload_url}}'
        asset_path: '${{github.workspace}}/install/${{matrix.source_asset}}'
        asset_name: '${{matrix.asset_name}}'
        asset_content_type: application/zip
